//!Imports
//Core node

//Custom
const User = require("../models/user");

//External

//=Controller functions

exports.getSignUp = (req, res) => {

    res.render("auth/signup", 
    {
        pageTitle: "Sign Up",
        path: "/signup",
        isLoggedIn: req.session.isLoggedIn

    });

}

exports.postSignUp = (req, res) => {

    //grab and store the new user details from post request generated by the form

    const username = req.body.username;
    const password = req.body.password;
    const repeatPassword = req.body.repeatPassword;

    //instantiate a new User object managed by mongoose
    const user = new User (

    {//supply it with the stored values
        username: username,
        password: password,
        repeatPassword: repeatPassword
    }
)
    //save the new user to the database with the mongoose method
    user.save()
    //then redirect the user to the home page
    .then(response => {
        res.redirect("/")
    })
    //catch any possible errors
    .catch(err => console.log(err));

}

exports.getLogin = (req, res) => {

    res.render("auth/login", 
    {
        pageTitle: "Log In",
        path: "/login",
        isLoggedIn: req.session.isLoggedIn

    });
    
}

exports.postLogin = (req, res) => {

    //find the user that just logged in by searching for the username they supplied
    User.find( { 'username' : { '$regex' : req.body.username, '$options' : 'i' } } )


    .then(user => {
        
        req.session.isLoggedIn = true; //add isLoggedIn cookie to the session
        req.session.user = user;//Add the user as user cookie to the session

        console.log(req.session.user);
        res.redirect("/");
    })

    .catch(err => console.log(err))

}

exports.getLogout = (req, res) => {

    //use the express session method to destroy the session and remove it from the database
    req.session.destroy((err) => {

        //console.log(err);
      
        res.redirect("/")
      
      })

}